### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by Dhravya**
Updated readme to have more modern badges, some extra links and table of content.

### CODE REVIEW

**Comment by nexxeln** [comment]
I liked the old badges tbh. Also I don't think we need badges for stars, forks and contributors. I like the original look of it. The rest I think is fine, just get rid of the emojis.
 >If you want to know more about the stack, check out [init.tips](https://init.tips/) or read the blog [by Nexxel](https://blog.nexxel.dev/create-t3-app)
 
 In this line just have the link for init.tips.
 
 In the Dev section add a link to CONTRIBUTING.md

**Comment by Dhravya** [comment]
alright will do

**Comment by nexxeln** [comment]
> pnpm create t3-app@latest

Also let's change this to ```pnpx create-t3-app@latest```

**Comment by nexxeln** [comment]
@Dhravya You can also add a logo. https://raw.githubusercontent.com/TheoBr/t3-astro/main/public/assets/t3-block.svg

**Comment by Dhravya** [comment]
ok that looks amazing

**Comment by asheeeshh** [comment]
> @Dhravya You can also add a logo. https://raw.githubusercontent.com/TheoBr/t3-astro/main/public/assets/t3-block.svg

try to make it rounded*

**Comment by asheeeshh** [comment]
here: https://s6.imgcdn.dev/BJW4B.png

**Comment by juliusmarminge** [comment]
perhaps some badges for the stack similar to this?
CleanShot 2022-06-27 at 20 01 07@2x

**Comment by Dhravya** [comment]
> here: https://s6.imgcdn.dev/BJW4B.png

I just used CSS to make it rounded lol

**Comment by nexxeln** [comment]
> perhaps some badges for the stack similar to this? [CleanShot 2022-06-27 at 20 01 07@2x ](https://github.com/juliusmarminge/sorting-visualizer#stack)

@Dhravya what do you think about this?

**Comment by nexxeln** [comment]
Yeah let's see how it looks. Do it.

**Comment by juliusmarminge** [comment]
I would style this more like the image above. There is a link embedded in the image, feel free to use that if you'd like.

**Comment by nexxeln** [comment]
I think we'll leave out those images. @Dhravya remove the latest commit and I'll merge

**Comment by nexxeln** [comment]
Thanks so much for being so patient! Merging now.

**Comment by Dhravya** [comment]
np! will keep contributing :P

**Comment by juliusmarminge** [comment]
## Stack

<div style="display: flex; gap: .25em;">
  <a href="https://www.typescriptlang.org">Typescript</a>
  <a href="https://trpc.io"></a>
  <a href="https://tailwindcss.com"></a>
  <a href="https://next-auth.js.org">TailwindCSS</a>
    <a href="https://prisma.io"></a>
</div>

something like this was what I had in mind

**Pull request merged**
