### PR TITLE
Adding full ESM support

### PR DESCRIPTION
**Pull request by MWhite-22**
Resolves issue #53 

BTW, bundled package went down from 10.5kb to 8kb just by switching over

### CODE REVIEW

**Comment by juliusmarminge** [comment]
why is `import x from "x/index.js"` required over `import x from "x"`?

**Comment by MWhite-22** [comment]
It actually comes up as a ts error as well. I HATE that i have to reference .js files in the import statement of a .ts, but thats literally just the way the standard works now.

**Comment by asheeeshh** [comment]
looks good, i had actually tried implementing this following sindre's gist but got confused midway

**Comment by nexxeln** [comment]
This looks good. Has this been tested properly?

**Comment by asheeeshh** [comment]
> This looks good. Has this been tested properly?

tested 👍🏼 

image

**Comment by nexxeln** [comment]
Cool, thank you

**Pull request merged**
