### PR TITLE
fix pacakage manager logic and add prettier option

### PR DESCRIPTION
**Pull request by asheeeshh**
~~added a new option to use prettier with the project with default config -~~

fixed the bug in package manager logic which was causing it to pick random package manager. temporary fix for #22

### CODE REVIEW

**Comment by nexxeln** [comment]
please remove prettier :pray:

**Comment by asheeeshh** [comment]
> please remove prettier 🙏

i though we discussed about it 🤔

**Comment by nexxeln** [comment]
i thought so too 🤔

**Comment by nexxeln** [comment]
thanks!

**Pull request merged**
