### PR TITLE
Adding in cli args, refactoring file structure, and changing prompts for inquirer

### PR DESCRIPTION
**Pull request by MWhite-22**
I went a little nuts, so, apologies, but i'll outline all the rationale below:

### Accepting args (#37 #50):
- Added commander as a parsing agent for the command line
- the first non-flagged argument will used as the app name and directory name
- Flags include:
  - `-y` or `--default`: Skips over the prompts and goes straight to initializing a new repo with opinionated defaults. Can still accept a directory argument so `npx create-t3-app myApp -y` will create a "default" app named "myApp" inside the "./myApp" directory
  - `--noGit`: Skip the git initialization step
  - `-v` or `--version`: Print the current create-t3-app version
  - `-h` or `--help`: All of this and more in a nicely formatted help menu

### Inquirer vs. Prompts:
- Inquirer has a much smaller package size and allows for assigning some generic types into the prompt instantiation. 
- Inquirer is slowly moving over to a full TS package where type safety will be massively improved
- Prompts was weirdly not exiting the CLI if the user pressed ctrl-c mid questions. Instead, it jumped straight into trying to run the scaffold scripts, which can't be cancelled once started. With inquirer, the user can press ctrl-c any time before the scaffolding starts, and the cli will correctly exit
- Inquirer comes with a check that the terminal is interactive. If not, it will throw a specific error. The current implementation catches that error, and will scaffold a default app for the user. This should help is someone not using an interactive terminal tries to use the cli and doesn't understand why no prompts are coming up.

### Add packages as a list, not individual questions (#42):
- Changed this question type to select from a list, rather than answer one by one
- Refactoring some of the installer types into an `as const` object means this list can be quickly and easily expanded in a type safe way

### A few bug fixes for ora (#47):
- Ora was blocking the scaffold function from asking the user if they wanted to overwrite a directory that already existed. Fixed those issues, and a few stylistic changes that bring the entire cli experience to a cohesive feel.

That should be everything. If you have any questions, please ask away.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
> On top of the above, I tried finding a way to easily add in a --noInstall flag to skip the actual install part of the scaffolding, but with the current architecture thats going to be really tough.

I guess a hack would be to just run a `rm -rf node_modules` afterwards. Can't believe there isn't an native argument like `npm install --add-only` for adding the latest version of a package to the package.json...

**Comment by nexxeln** [comment]
I think `--noInstall` can be implemented later when the layouts RFC thing comes out. We will have kind of rewrite then anyway. Fo now I think not having this is fine.

**Comment by nexxeln** [comment]
@MWhite-22 Can you also please unselect all of the prompts by default

**Comment by nexxeln** [comment]
No, what I meant was that in the prompts to select the packages, initially nothing should be selected.

**Comment by MWhite-22** [comment]
Right right, but I am building those choices programmatically from the "default" option.

So the new build will have all packages by `-y` default, but if they user is going through the prompts, the prompts will start off will all packages deselected. Correct?

**Comment by MWhite-22** [comment]
Rebased to the new readme doc

**Comment by nexxeln** [comment]
Looks good! Very good PR. Thank you so much

**Comment by MWhite-22** [comment]
It does! Any name arg is passed in still, but the interactive part (aka: the fun language selector, and the packages selector) will not be viewable.

**Comment by MWhite-22** [comment]
Never mind, I now see what you mean. Updating the string template to ${cliResults.appName}

**Pull request merged**
